// Generated by gencpp from file oculus_msgs/Button_state.msg
// DO NOT EDIT!


#ifndef OCULUS_MSGS_MESSAGE_BUTTON_STATE_H
#define OCULUS_MSGS_MESSAGE_BUTTON_STATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Float32.h>
#include <std_msgs/Float32.h>
#include <geometry_msgs/Vector3.h>
#include <std_msgs/Int8.h>
#include <std_msgs/Int8.h>
#include <std_msgs/Int8.h>

namespace oculus_msgs
{
template <class ContainerAllocator>
struct Button_state_
{
  typedef Button_state_<ContainerAllocator> Type;

  Button_state_()
    : IndexTrigger()
    , HandTrigger()
    , Thumbstick()
    , AX()
    , BY()
    , Thumb()  {
    }
  Button_state_(const ContainerAllocator& _alloc)
    : IndexTrigger(_alloc)
    , HandTrigger(_alloc)
    , Thumbstick(_alloc)
    , AX(_alloc)
    , BY(_alloc)
    , Thumb(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Float32_<ContainerAllocator>  _IndexTrigger_type;
  _IndexTrigger_type IndexTrigger;

   typedef  ::std_msgs::Float32_<ContainerAllocator>  _HandTrigger_type;
  _HandTrigger_type HandTrigger;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _Thumbstick_type;
  _Thumbstick_type Thumbstick;

   typedef  ::std_msgs::Int8_<ContainerAllocator>  _AX_type;
  _AX_type AX;

   typedef  ::std_msgs::Int8_<ContainerAllocator>  _BY_type;
  _BY_type BY;

   typedef  ::std_msgs::Int8_<ContainerAllocator>  _Thumb_type;
  _Thumb_type Thumb;





  typedef boost::shared_ptr< ::oculus_msgs::Button_state_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::oculus_msgs::Button_state_<ContainerAllocator> const> ConstPtr;

}; // struct Button_state_

typedef ::oculus_msgs::Button_state_<std::allocator<void> > Button_state;

typedef boost::shared_ptr< ::oculus_msgs::Button_state > Button_statePtr;
typedef boost::shared_ptr< ::oculus_msgs::Button_state const> Button_stateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::oculus_msgs::Button_state_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::oculus_msgs::Button_state_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace oculus_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'oculus_msgs': ['/home/hsrnote/catkin_ws/src/oculus_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::oculus_msgs::Button_state_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::oculus_msgs::Button_state_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::oculus_msgs::Button_state_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::oculus_msgs::Button_state_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::oculus_msgs::Button_state_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::oculus_msgs::Button_state_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::oculus_msgs::Button_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1298ce2454f78924d1a5e6f157e54015";
  }

  static const char* value(const ::oculus_msgs::Button_state_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1298ce2454f78924ULL;
  static const uint64_t static_value2 = 0xd1a5e6f157e54015ULL;
};

template<class ContainerAllocator>
struct DataType< ::oculus_msgs::Button_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "oculus_msgs/Button_state";
  }

  static const char* value(const ::oculus_msgs::Button_state_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::oculus_msgs::Button_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Float32 IndexTrigger\n\
std_msgs/Float32 HandTrigger\n\
geometry_msgs/Vector3 Thumbstick\n\
std_msgs/Int8 AX\n\
std_msgs/Int8 BY\n\
std_msgs/Int8 Thumb\n\
\n\
================================================================================\n\
MSG: std_msgs/Float32\n\
float32 data\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
================================================================================\n\
MSG: std_msgs/Int8\n\
int8 data\n\
";
  }

  static const char* value(const ::oculus_msgs::Button_state_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::oculus_msgs::Button_state_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.IndexTrigger);
      stream.next(m.HandTrigger);
      stream.next(m.Thumbstick);
      stream.next(m.AX);
      stream.next(m.BY);
      stream.next(m.Thumb);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Button_state_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::oculus_msgs::Button_state_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::oculus_msgs::Button_state_<ContainerAllocator>& v)
  {
    s << indent << "IndexTrigger: ";
    s << std::endl;
    Printer< ::std_msgs::Float32_<ContainerAllocator> >::stream(s, indent + "  ", v.IndexTrigger);
    s << indent << "HandTrigger: ";
    s << std::endl;
    Printer< ::std_msgs::Float32_<ContainerAllocator> >::stream(s, indent + "  ", v.HandTrigger);
    s << indent << "Thumbstick: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.Thumbstick);
    s << indent << "AX: ";
    s << std::endl;
    Printer< ::std_msgs::Int8_<ContainerAllocator> >::stream(s, indent + "  ", v.AX);
    s << indent << "BY: ";
    s << std::endl;
    Printer< ::std_msgs::Int8_<ContainerAllocator> >::stream(s, indent + "  ", v.BY);
    s << indent << "Thumb: ";
    s << std::endl;
    Printer< ::std_msgs::Int8_<ContainerAllocator> >::stream(s, indent + "  ", v.Thumb);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OCULUS_MSGS_MESSAGE_BUTTON_STATE_H
