// Generated by gencpp from file oculus_msgs/Oculus_touch.msg
// DO NOT EDIT!


#ifndef OCULUS_MSGS_MESSAGE_OCULUS_TOUCH_H
#define OCULUS_MSGS_MESSAGE_OCULUS_TOUCH_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <oculus_msgs/Touch_sensor.h>
#include <oculus_msgs/Touch_sensor.h>

namespace oculus_msgs
{
template <class ContainerAllocator>
struct Oculus_touch_
{
  typedef Oculus_touch_<ContainerAllocator> Type;

  Oculus_touch_()
    : header()
    , left()
    , right()  {
    }
  Oculus_touch_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , left(_alloc)
    , right(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::oculus_msgs::Touch_sensor_<ContainerAllocator>  _left_type;
  _left_type left;

   typedef  ::oculus_msgs::Touch_sensor_<ContainerAllocator>  _right_type;
  _right_type right;





  typedef boost::shared_ptr< ::oculus_msgs::Oculus_touch_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::oculus_msgs::Oculus_touch_<ContainerAllocator> const> ConstPtr;

}; // struct Oculus_touch_

typedef ::oculus_msgs::Oculus_touch_<std::allocator<void> > Oculus_touch;

typedef boost::shared_ptr< ::oculus_msgs::Oculus_touch > Oculus_touchPtr;
typedef boost::shared_ptr< ::oculus_msgs::Oculus_touch const> Oculus_touchConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::oculus_msgs::Oculus_touch_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::oculus_msgs::Oculus_touch_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace oculus_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'oculus_msgs': ['/home/hsrnote/catkin_ws/src/oculus_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::oculus_msgs::Oculus_touch_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::oculus_msgs::Oculus_touch_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::oculus_msgs::Oculus_touch_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::oculus_msgs::Oculus_touch_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::oculus_msgs::Oculus_touch_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::oculus_msgs::Oculus_touch_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::oculus_msgs::Oculus_touch_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9750824d398b8b30e993fba78278b10f";
  }

  static const char* value(const ::oculus_msgs::Oculus_touch_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9750824d398b8b30ULL;
  static const uint64_t static_value2 = 0xe993fba78278b10fULL;
};

template<class ContainerAllocator>
struct DataType< ::oculus_msgs::Oculus_touch_<ContainerAllocator> >
{
  static const char* value()
  {
    return "oculus_msgs/Oculus_touch";
  }

  static const char* value(const ::oculus_msgs::Oculus_touch_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::oculus_msgs::Oculus_touch_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
oculus_msgs/Touch_sensor left\n\
oculus_msgs/Touch_sensor right\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: oculus_msgs/Touch_sensor\n\
geometry_msgs/Pose pose\n\
geometry_msgs/Twist velocity\n\
geometry_msgs/Accel acceleration\n\
oculus_msgs/Button_state button\n\
oculus_msgs/Button_touch_state touch\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Twist\n\
# This expresses velocity in free space broken into its linear and angular parts.\n\
Vector3  linear\n\
Vector3  angular\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
================================================================================\n\
MSG: geometry_msgs/Accel\n\
# This expresses acceleration in free space broken into its linear and angular parts.\n\
Vector3  linear\n\
Vector3  angular\n\
\n\
================================================================================\n\
MSG: oculus_msgs/Button_state\n\
std_msgs/Float32 IndexTrigger\n\
std_msgs/Float32 HandTrigger\n\
geometry_msgs/Vector3 Thumbstick\n\
std_msgs/Int8 AX\n\
std_msgs/Int8 BY\n\
std_msgs/Int8 Thumb\n\
\n\
================================================================================\n\
MSG: std_msgs/Float32\n\
float32 data\n\
================================================================================\n\
MSG: std_msgs/Int8\n\
int8 data\n\
\n\
================================================================================\n\
MSG: oculus_msgs/Button_touch_state\n\
std_msgs/Int8 AX\n\
std_msgs/Int8 BY\n\
std_msgs/Int8 Thumb\n\
std_msgs/Int8 ThumbRest\n\
std_msgs/Int8 IndexTrigger\n\
std_msgs/Int8 IndexPointing\n\
std_msgs/Int8 ThumbUp\n\
\n\
";
  }

  static const char* value(const ::oculus_msgs::Oculus_touch_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::oculus_msgs::Oculus_touch_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.left);
      stream.next(m.right);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Oculus_touch_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::oculus_msgs::Oculus_touch_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::oculus_msgs::Oculus_touch_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "left: ";
    s << std::endl;
    Printer< ::oculus_msgs::Touch_sensor_<ContainerAllocator> >::stream(s, indent + "  ", v.left);
    s << indent << "right: ";
    s << std::endl;
    Printer< ::oculus_msgs::Touch_sensor_<ContainerAllocator> >::stream(s, indent + "  ", v.right);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OCULUS_MSGS_MESSAGE_OCULUS_TOUCH_H
