// Generated by gencpp from file oculus_msgs/Oculus_haptic.msg
// DO NOT EDIT!


#ifndef OCULUS_MSGS_MESSAGE_OCULUS_HAPTIC_H
#define OCULUS_MSGS_MESSAGE_OCULUS_HAPTIC_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <std_msgs/Float32.h>
#include <std_msgs/Float32.h>

namespace oculus_msgs
{
template <class ContainerAllocator>
struct Oculus_haptic_
{
  typedef Oculus_haptic_<ContainerAllocator> Type;

  Oculus_haptic_()
    : header()
    , left()
    , right()  {
    }
  Oculus_haptic_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , left(_alloc)
    , right(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::std_msgs::Float32_<ContainerAllocator>  _left_type;
  _left_type left;

   typedef  ::std_msgs::Float32_<ContainerAllocator>  _right_type;
  _right_type right;





  typedef boost::shared_ptr< ::oculus_msgs::Oculus_haptic_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::oculus_msgs::Oculus_haptic_<ContainerAllocator> const> ConstPtr;

}; // struct Oculus_haptic_

typedef ::oculus_msgs::Oculus_haptic_<std::allocator<void> > Oculus_haptic;

typedef boost::shared_ptr< ::oculus_msgs::Oculus_haptic > Oculus_hapticPtr;
typedef boost::shared_ptr< ::oculus_msgs::Oculus_haptic const> Oculus_hapticConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::oculus_msgs::Oculus_haptic_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::oculus_msgs::Oculus_haptic_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace oculus_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'oculus_msgs': ['/home/hsrnote/catkin_ws/src/oculus_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::oculus_msgs::Oculus_haptic_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::oculus_msgs::Oculus_haptic_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::oculus_msgs::Oculus_haptic_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::oculus_msgs::Oculus_haptic_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::oculus_msgs::Oculus_haptic_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::oculus_msgs::Oculus_haptic_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::oculus_msgs::Oculus_haptic_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cae2efafc994c01b48c1a93dec4858a8";
  }

  static const char* value(const ::oculus_msgs::Oculus_haptic_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcae2efafc994c01bULL;
  static const uint64_t static_value2 = 0x48c1a93dec4858a8ULL;
};

template<class ContainerAllocator>
struct DataType< ::oculus_msgs::Oculus_haptic_<ContainerAllocator> >
{
  static const char* value()
  {
    return "oculus_msgs/Oculus_haptic";
  }

  static const char* value(const ::oculus_msgs::Oculus_haptic_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::oculus_msgs::Oculus_haptic_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
std_msgs/Float32 left\n\
std_msgs/Float32 right\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: std_msgs/Float32\n\
float32 data\n\
";
  }

  static const char* value(const ::oculus_msgs::Oculus_haptic_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::oculus_msgs::Oculus_haptic_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.left);
      stream.next(m.right);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Oculus_haptic_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::oculus_msgs::Oculus_haptic_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::oculus_msgs::Oculus_haptic_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "left: ";
    s << std::endl;
    Printer< ::std_msgs::Float32_<ContainerAllocator> >::stream(s, indent + "  ", v.left);
    s << indent << "right: ";
    s << std::endl;
    Printer< ::std_msgs::Float32_<ContainerAllocator> >::stream(s, indent + "  ", v.right);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OCULUS_MSGS_MESSAGE_OCULUS_HAPTIC_H
